name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_with_versions.txt
          python -m playwright install --with-deps

      - name: Run Playwright tests
        run: |
          mkdir -p allure-report
          mkdir -p allure-results
          mkdir -p screenshots
          pytest --alluredir=allure-results --capture=tee-sys --reruns 2 --reruns-delay 5 -m smoke -n 4  || true

      - name: Generate Test Results
        run: allure generate allure-results -o allure-report --clean --single-file

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-report/
          retention-days: 30
